"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var react_1 = require("react");
var MenuIcons_1 = require("../components/menu/MenuIcons");
var ThemeContext_1 = require("../context/ThemeContext");
var react_router_1 = require("react-router");
var Sidebar = function () {
    var _a = (0, react_1.useState)(true), width = _a[0], setWidth = _a[1];
    var theme = (0, react_1.useContext)(ThemeContext_1.ThemeContext).theme;
    return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)("aside", { children: (0, jsx_runtime_1.jsxs)("div", { className: "".concat(width === true ? 'w-12' : 'w-36', " row-all flex flex-col justify-between items-start min-h-dvh  shadow-2xl px-3 mx-3 my-3 fixed z-10 ").concat(theme === 'light' ? 'bg-white text-black' : 'bg-[#171717] text-white'), children: [(0, jsx_runtime_1.jsx)("div", { className: 'row-1', children: MenuIcons_1.MenuIconsRow.map(function (item) { return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)("div", { className: 'flex justify-start items-center gap-3 gap-y-5 cursor-pointer hover:text-blue-800 my-10', children: width ? ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [' ', (0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', onClick: function () {
                                                setWidth(!width);
                                            }, children: item.icon })] })) : ((0, jsx_runtime_1.jsxs)(jsx_runtime_1.Fragment, { children: [' ', (0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', onClick: function () {
                                                setWidth(!width);
                                            }, children: item.icon }), (0, jsx_runtime_1.jsx)("p", { className: 'font-semibold', children: item.title })] })) }) })); }) }), (0, jsx_runtime_1.jsx)("div", { className: 'row-2', children: MenuIcons_1.MenuIconsRow1.map(function (item) { return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)("div", { className: 'flex justify-start items-center gap-3 gap-y-5 cursor-pointer hover:text-blue-800 my-10', children: width ? ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: item.link, children: (0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', children: item.icon }) }) })) : ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsxs)(react_router_1.Link, { to: item.link, className: 'flex justify-start items-center gap-3 gap-y-5', children: [(0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', children: item.icon }), (0, jsx_runtime_1.jsx)("p", { className: 'font-semibold', children: item.title })] }) })) }) })); }) }), (0, jsx_runtime_1.jsx)("div", { className: 'row-3', children: MenuIcons_1.MenuIconsRow2.map(function (item) { return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)("div", { className: 'flex justify-start items-center gap-3 gap-y-5 cursor-pointer hover:text-blue-800 my-10', children: width ? ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: item.link, children: (0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', children: item.icon }) }) })) : ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsxs)(react_router_1.Link, { to: item.link, className: 'flex justify-start items-center gap-3 gap-y-5', children: [(0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', children: item.icon }), (0, jsx_runtime_1.jsx)("p", { className: 'font-semibold', children: item.title })] }) })) }) })); }) }), (0, jsx_runtime_1.jsx)("div", { className: 'row-4', children: MenuIcons_1.MenuIconsRow3.map(function (item) { return ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)("div", { className: 'hover:text-blue-800 my-10', children: width ? ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsx)(react_router_1.Link, { to: item.link, children: (0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', children: item.icon }) }) })) : ((0, jsx_runtime_1.jsx)(jsx_runtime_1.Fragment, { children: (0, jsx_runtime_1.jsxs)(react_router_1.Link, { to: item.link, className: 'flex justify-start items-center gap-3 gap-y-5', children: [(0, jsx_runtime_1.jsx)("p", { className: 'text-2xl', children: item.icon }), (0, jsx_runtime_1.jsx)("p", { className: 'font-semibold', children: item.title })] }) })) }) })); }) })] }) }) }));
};
exports.default = Sidebar;
